-- AlterTable
ALTER TABLE `categories` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `permissions` MODIFY `group` ENUM('USER', 'ROLE', 'PERMISSION', 'SETTING', 'LOGGER', 'BLOG', 'REPOSITORY', 'CATEGORY') NOT NULL;
