# docker-compose.yml
version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: teradose-api
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      # App
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_LANGUAGE=${APP_LANGUAGE}
      
      # HTTP
      - HTTP_ENABLE=${HTTP_ENABLE}
      - HTTP_HOST=${HTTP_HOST}
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_VERSIONING_ENABLE=${HTTP_VERSIONING_ENABLE}
      - HTTP_VERSION=${HTTP_VERSION}
      
      # Debugger
      - DEBUGGER_HTTP_WRITE_INTO_FILE=${DEBUGGER_HTTP_WRITE_INTO_FILE}
      - DEBUGGER_HTTP_WRITE_INTO_CONSOLE=${DEBUGGER_HTTP_WRITE_INTO_CONSOLE}
      - DEBUGGER_SYSTEM_WRITE_INTO_FILE=${DEBUGGER_SYSTEM_WRITE_INTO_FILE}
      - DEBUGGER_SYSTEM_WRITE_INTO_CONSOLE=${DEBUGGER_SYSTEM_WRITE_INTO_CONSOLE}
      
      # Job
      - JOB_ENABLE=${JOB_ENABLE}
      
      # Auth JWT
      - AUTH_JWT_SUBJECT=${AUTH_JWT_SUBJECT}
      - AUTH_JWT_ISSUER=${AUTH_JWT_ISSUER}
      - AUTH_JWT_AUDIENCE=${AUTH_JWT_AUDIENCE}
      - AUTH_JWT_ACCESS_TOKEN_SECRET_KEY=${AUTH_JWT_ACCESS_TOKEN_SECRET_KEY}
      - AUTH_JWT_ACCESS_TOKEN_EXPIRED=${AUTH_JWT_ACCESS_TOKEN_EXPIRED}
      - AUTH_JWT_REFRESH_TOKEN_SECRET_KEY=${AUTH_JWT_REFRESH_TOKEN_SECRET_KEY}
      - AUTH_JWT_REFRESH_TOKEN_EXPIRED=${AUTH_JWT_REFRESH_TOKEN_EXPIRED}
      - AUTH_JWT_REFRESH_TOKEN_REMEMBER_ME_EXPIRED=${AUTH_JWT_REFRESH_TOKEN_REMEMBER_ME_EXPIRED}
      - AUTH_JWT_REFRESH_TOKEN_NOT_BEFORE_EXPIRATION=${AUTH_JWT_REFRESH_TOKEN_NOT_BEFORE_EXPIRATION}
      
      # Auth Permission
      - AUTH_PERMISSION_TOKEN_SECRET_KEY=${AUTH_PERMISSION_TOKEN_SECRET_KEY}
      - AUTH_PERMISSION_TOKEN_EXPIRED=${AUTH_PERMISSION_TOKEN_EXPIRED}
      
      # Auth JWT Payload
      - AUTH_JWT_PAYLOAD_ENCRYPT=${AUTH_JWT_PAYLOAD_ENCRYPT}
      - AUTH_JWT_PAYLOAD_ACCESS_TOKEN_ENCRYPT_KEY=${AUTH_JWT_PAYLOAD_ACCESS_TOKEN_ENCRYPT_KEY}
      - AUTH_JWT_PAYLOAD_ACCESS_TOKEN_ENCRYPT_IV=${AUTH_JWT_PAYLOAD_ACCESS_TOKEN_ENCRYPT_IV}
      - AUTH_JWT_PAYLOAD_REFRESH_TOKEN_ENCRYPT_KEY=${AUTH_JWT_PAYLOAD_REFRESH_TOKEN_ENCRYPT_KEY}
      - AUTH_JWT_PAYLOAD_REFRESH_TOKEN_ENCRYPT_IV=${AUTH_JWT_PAYLOAD_REFRESH_TOKEN_ENCRYPT_IV}
      - AUTH_PAYLOAD_PERMISSION_TOKEN_ENCRYPT_KEY=${AUTH_PAYLOAD_PERMISSION_TOKEN_ENCRYPT_KEY}
      - AUTH_PAYLOAD_PERMISSION_TOKEN_ENCRYPT_IV=${AUTH_PAYLOAD_PERMISSION_TOKEN_ENCRYPT_IV}
      
      # AWS
      - AWS_CREDENTIAL_KEY=${AWS_CREDENTIAL_KEY}
      - AWS_CREDENTIAL_SECRET=${AWS_CREDENTIAL_SECRET}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      
      # Database
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
    
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network


networks:
  app-network:
    driver: bridge