export enum ENUM_REPOSITORIES_STATUS_CODE_ERROR {
    REPOSITORIES_NOT_FOUND_ERROR = 5700,
    REPOSITORIES_EXIST_ERROR = 5701,
    REPOSITORIES_IS_ACTIVE_ERROR = 5702,
    REPOSITORIES_INACTIVE_ERROR = 5703,
    REPOSITORIES_USED_ERROR = 5704,
    REPOSITORIES_IS_NOT_ACTIVE_ERROR = 5705,
    REPOSITORIES_STATUS_ERROR = 5706,
    REPOSITORIES_STATUS_INVALID_ERROR = 5707,
    REPOSITORIES_STATUS_NOT_FOUND_ERROR = 5708,
    REPOSITORY_CATEGORIES_NOT_FOUND_ERROR = 5709,
    REPOSITORY_CATEGORIES_EXIST_ERROR = 5710,
    
}
