export enum ENUM_REPOSITORIES_STATUS {
    DRAFT = 'DRAFT',
    PUBLISHED = 'PUBLISHED',
    ARCHIVED = 'ARCHIVED',
}

export const ENUM_REPOSITORIES_STATUS_LIST = {
    ...ENUM_REPOSITORIES_STATUS,
};
export type ENUM_REPOSITORIES_STATUS_LIST = ENUM_REPOSITORIES_STATUS;
export const ENUM_REPOSITORIES_TYPE = Object.values(ENUM_REPOSITORIES_STATUS);
